### ISSUE TITLE
how to iso chrome push?

### ISSUE THREAD

**Issue by Terrorboy** [one-signal/OneSignal-Website-SDK#1]
how to iso chrome push?

**Comment by jkasten2** [comment]
Hello,

You can follow our [Website push overview guide](https://documentation.onesignal.com/docs/website-sdk-overview) to get started. We also have a [Wordpress plugin](https://wordpress.org/plugins/onesignal-free-web-push-notifications/).

Thanks.

**Comment by jkasten2** [comment]
If you have any further questions you can reopen this issue.

**Comment by Terrorboy** [comment]
@jkasten2 Tnk!
