### ISSUE TITLE
getIdsAvailable return data even I deleted this user on onesignal user page

### ISSUE THREAD

**Issue by thucnc** [one-signal/OneSignal-Website-SDK#2]
I tried to delete user on onesignal page but the javascript api "getIdsAvailable" still returns data. My purpose is to check if user is already registered on onesignal.
Please help

**Comment by jkasten2** [comment]
The Delete button on the User dashboard is designed to clean up old test users. You shouldn't use it for production users. getIdsAvailable will return a cached value as the userId should not change after the first registration.

If your looking to test your site as a new user please follow our [Fully reset to test as a new User](https://documentation.onesignal.com/docs/website-push-common-problems#fully-reset-to-test-as-a-new-user) guide.

Thanks.
